server:
  port: 14120
coc:
  jwt: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImEzNGY5YWQ4LWRlMWYtNGRmNC1hYmM3LWIzNDliODk0ZTM2NCIsImlhdCI6MTYzNzY1OTcxMSwic3ViIjoiZGV2ZWxvcGVyLzkxZWRmZDJjLTJiMGMtNDYwZi00NTM5LTM4MzMwMjE1ZDc4MiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEyMC4yNDIuMjUyLjIxMiIsIjEyMC4yNDIuMjUzLjM5Il0sInR5cGUiOiJjbGllbnQifV19.V-fzV5k5P6-jPNe0T8G1I7ZfGdX6nzv0K9GaUlyqgwMs3vM_c_EQrZWXgmraKxsBebCtK1K7_oyjC3UDmbXwlw
  prefix: https://api.clashofclans.com/v1
